dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
script:
  - npm run test:unit
  - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $FINANCE_CALCULATOR_GITHUB_TOKEN
    keep-history: true
    local-dir: dist
    on:
        branch: master
